
modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"


[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}-common.mixins.json"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "icon.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
    modUrl = "${mod_homepage}"
    itemIcon = "supplementaries:globe" #catalogue icon

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_min_version},${minecraft_max_version})"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "moonlight"
    type = "required"
    referralUrl = "https://www.curseforge.com/minecraft/mc-mods/selene"
    versionRange = "[${moonlight_version_range},]"
    ordering = "NONE"
    side = "BOTH"

["lithium:options"]
    block.moving_block_shapes = false
    mixin.block.moving_block_shapes = false
    mixins.block.moving_block_shapes = false


